-- MySQL Script generated by MySQL Workbench
-- Thu Jun  1 14:24:40 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';



-- -----------------------------------------------------
-- Table `posters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posters`(
  `poster_id` INT NOT NULL AUTO_INCREMENT,
  `poster_text` TEXT,
  `poster_date` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `id_color` INT NOT NULL,
  PRIMARY KEY (`poster_id`),
  FOREIGN KEY (`id_color`) REFERENCES `colors`(`color_id`));


-- -----------------------------------------------------
-- Table `colors`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `colors`(
  `color_id` INT NOT NULL AUTO_INCREMENT,
  `color_name` VARCHAR(30) NOT NULL,
  `color_code` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`color_id`));



-- -----------------------------------------------------
-- Ajout des colors
-- -----------------------------------------------------

INSERT INTO colors (color_name, color_code)
VALUES ('orange', '#FFC972'),
       ('salmon', '#FF9B73'),
       ('purple', '#B692FE'),
       ('blue', '#01D4FF'),
       ('fadegreen', '#E4EE91');


